### ISSUE TITLE
[style] internships sorting 

### ISSUE THREAD

**Issue by aboueleyes** [ACM-Alexandria-SC/Internships#10]
The alphabetical sorting has some problems 
- `hard to spot` new internships 
- does not add a lot of info about when it's was added and so on

I guess sorting with newly added will be better as every time I open the repo, `I can know what are the newly added internships.` 

> Possible Solution 

is to have 2 different `branches`  one sorted by 
- `date of insertion` 
- `lexigorically` 
and have a GitHub bot to manage that.

**Comment by ahr9n** [comment]
Or to specify modifications in commit messages, mentioning names of internships. Like in: [d3ebf3c](https://github.com/ACM-Alexandria-SC/Internships/commit/d3ebf3cc784ce93be2c7c391372a6dfe24f742c3)

**Comment by aboueleyes** [comment]
> Or to specify modifications in commit messages, mentioning names of internships. Like in: [d3ebf3c](https://github.com/ACM-Alexandria-SC/Internships/commit/d3ebf3cc784ce93be2c7c391372a6dfe24f742c3)
@ahr9n 

I thought about but it's not the best way as i don't have to go through the repo commit history

However, I agree with you, anyways there has to be a commit message convention.

**Comment by MaiAhmedHussein** [comment]
> Or to specify modifications in commit messages, mentioning names of internships. Like in: [d3ebf3c](https://github.com/ACM-Alexandria-SC/Internships/commit/d3ebf3cc784ce93be2c7c391372a6dfe24f742c3)

I believe we are doing so....except if we are just editing/updating not adding a new intern.

**Comment by MaiAhmedHussein** [comment]
> The alphabetical sorting has some problems
> 
> * `hard to spot` new internships
> * does not add a lot of info about when it's was added and so on
> 
> I guess sorting with newly added will be better as every time I open the repo, `I can know what are the newly added internships.`
> 
> > Possible Solution
> 
> is to have 2 different `branches` one sorted by
> 
> * `date of insertion`
> * `lexigorically`
>   and have a GitHub bot to manage that.

I think you can fork the repo, and every time you open it, you can merge the new commits and you will see the added/closed interns commits named by the interns' names.

**Comment by aboueleyes** [comment]
> > The alphabetical sorting has some problems
> > 
> > * `hard to spot` new internships
> > * does not add a lot of info about when it's was added and so on
> > 
> > I guess sorting with newly added will be better as every time I open the repo, `I can know what are the newly added internships.`
> > > Possible Solution
> > 
> > 
> > is to have 2 different `branches` one sorted by
> > 
> > * `date of insertion`
> > * `lexigorically`
> >   and have a GitHub bot to manage that.
> 
> I think you can fork the repo, and every time you open it, you can merge the new commits and you will see the added/closed interns commits named by the interns' names.

seems a lot of work, making it easy for everyone would be something nice to do : )

**Comment by aboueleyes** [comment]
> 

good job : ).

But I believe having a  standard will make it even better for example 

[operation] [internship name] [internship index]

operation can  include 
- Add -> add new internship 
- Update -> update Esxistig one 
- Archive -> move to archive list 

[Archive] Microsoft SWE intern #10 
[Add] Facebook DS intern  #14 

and so on.,

**Comment by MaiAhmedHussein** [comment]
> > 
> 
> good job : ).
> 
> But I believe having a standard will make it even better for example
> 
> [operation] [internship name] [internship index]
> 
> operation can include
> 
> * Add -> add new internship
> * Update -> update Esxistig one
> * Archive -> move to archive list
> 
> [Archive] Microsoft SWE intern #10 [Add] Facebook DS intern #14
> 
> and so on.,

Great Idea!! 
We will try to do so :)

**Comment by Bazina** [comment]
> The alphabetical sorting has some problems
> 
> * `hard to spot` new internships
> * does not add a lot of info about when it's was added and so on
> 
> I guess sorting with newly added will be better as every time I open the repo, `I can know what are the newly added internships.`
> 
> > Possible Solution
> 
> is to have 2 different `branches` one sorted by
> 
> * `date of insertion`
> * `lexigorically`
>   and have a GitHub bot to manage that.

- You have a point, these two ways of sorting will make it better but almost all the interns open at the same time, so it won't have that potential, so we preferred lexicographically.
- According to the commits, we will work on improving it, so it is clearer than before.
Thanks for your time ❤.

**Comment by aboueleyes** [comment]
> > The alphabetical sorting has some problems
> > 
> > * `hard to spot` new internships
> > * does not add a lot of info about when it's was added and so on
> > 
> > I guess sorting with newly added will be better as every time I open the repo, `I can know what are the newly added internships.`
> > > Possible Solution
> > 
> > 
> > is to have 2 different `branches` one sorted by
> > 
> > * `date of insertion`
> > * `lexigorically`
> >   and have a GitHub bot to manage that.
> 
>     * You have a point, these two ways of sorting will make it better but almost all the interns open at the same time, so it won't have that potential, so we preferred lexicographically.
> 
>     * According to the commits, we will work on improving it, so it is clearer than before.
>       Thanks for your time heart.

I guess you misunderstood me for the sorting by adding, 
I am not talking about the company posting the internship, I'm talking about when It's added to the repo. 
Why is this useful?

when I open the repo, I go look for the internships that are recently added by you, to go and apply, it would have been way easier if I just went to the tail of the md file and applied for those.

anyways Thank you for your time <3

**Comment by MaiAhmedHussein** [comment]
> > > The alphabetical sorting has some problems
> > > 
> > > * `hard to spot` new internships
> > > * does not add a lot of info about when it's was added and so on
> > > 
> > > I guess sorting with newly added will be better as every time I open the repo, `I can know what are the newly added internships.`
> > > > Possible Solution
> > > 
> > > 
> > > is to have 2 different `branches` one sorted by
> > > 
> > > * `date of insertion`
> > > * `lexigorically`
> > >   and have a GitHub bot to manage that.
> > 
> > 
> > ```
> > * You have a point, these two ways of sorting will make it better but almost all the interns open at the same time, so it won't have that potential, so we preferred lexicographically.
> > 
> > * According to the commits, we will work on improving it, so it is clearer than before.
> >   Thanks for your time heart.
> > ```
> 
> I guess you misunderstood me for the sorting by adding, I am not talking about the company posting the internship, I'm talking about when It's added to the repo. Why is this useful?
> 
> when I open the repo, I go look for the internships that are recently added by you, to go and apply, it would have been way easier if I just went to the tail of the md file and applied for those.
> 
> anyways Thank you for your time <3

You mean changing the commits messages to a standard form, right?

**Comment by aboueleyes** [comment]
> 

I mean sorting the table by the time of adding for example 

| intern name |
| -- |  
| A | 
| C | 

if insert `B` now your approach is 
| intern name |
| -- |  
| A | 
| B |
| C | 

however, mine is 
| intern name |
| -- |  
| A | 
| C | 
| B |

why is this useful? when I open the repo just looking for the tail of the table i knew what internships I haven't applied yet.

**Comment by MaiAhmedHussein** [comment]
> > 
> 
> I mean sorting the table by the time of adding for example
> 
> intern name
> A
> C
> if insert `B` now your approach is
> 
> intern name
> A
> B
> C
> however, mine is
> 
> intern name
> A
> C
> B
> why is this useful? when I open the repo just looking for the tail of the table i knew what internships I haven't applied yet.

Yea, I got it. I mean the previous suggestion of "[operation] [internship name] [internship index]" 
You were concerning the commits messages ?

**Comment by aboueleyes** [comment]
> > > 
> > 
> > 
> > I mean sorting the table by the time of adding for example
> > intern name
> > A
> > C
> > if insert `B` now your approach is
> > intern name
> > A
> > B
> > C
> > however, mine is
> > intern name
> > A
> > C
> > B
> > why is this useful? when I open the repo just looking for the tail of the table i knew what internships I haven't applied yet.
> 
> Yea, I got it. I mean the previous suggestion of "[operation] [internship name] [internship index]" You were concerning the commits messages ?

yes.
