### ISSUE TITLE
Sort by dates 

### ISSUE THREAD

**Issue by elarabyelaidy19** [ACM-Alexandria-SC/Internships#16]
I found it intuitive and more usable to sort by dates, it's overwhelming to go over all openings and figure out which one I applied for and which one I did not.

**Comment by Yasien99** [comment]
>  Isn't the status column enough? you can fork the repo and add your own status like applied or accepted or rejected.

How can I resolve the merge conflicts when my branch is 9 commits behind the upstream and has conflicts that must be resolved?
I just added my status in each row.

**Comment by moaz-eldefrawy** [comment]
> How can I resolve the merge conflicts when my branch is 9 commits behind the upstream .. 
You can rebase instead of merge, but It's not the most convenient solution tbh. Do you have any ideas?

**Comment by Yasien99** [comment]
> You can rebase instead of merge, but It's not the most convenient solution tbh. Do you have any ideas?

I guess conflicts will always be there, so I guess sorting by dates will be more intuitive.
You can make it an ordered list, so for example, I can know that I applied till the internship number 30 in the table.
I now check the commit log to know what internship I missed.

**Comment by Ammar000x** [comment]
> > You can rebase instead of merge, but It's not the most convenient solution tbh. Do you have any ideas?
> 
> I guess conflicts will always be there, so I guess sorting by dates will be more intuitive. You can make it an ordered list, so for example, I can know that I applied till the internship number 30 in the table. I now check the commit log to know what internship I missed.

yes, I think this is the right choice to make, as when I want to check, I will check the last of md.file, and do not check if someone enters any intern in the middle of the file

**Comment by moaz-eldefrawy** [comment]
Thank you guys for the feedback ❤🙏. We will do that next year ISA.
