### ISSUE TITLE
Adding Stack Info

### ISSUE THREAD

**Issue by shehabadel** [ACM-Alexandria-SC/Internships#26]
Stack Info is a platform that shows tech stack of more than 175 startups and corporates in Egypt.

We can add [Stack Info](www.stackinfo.me) in `README.md` so anyone can check tech stack of a specific company before applying to an internship.

**Comment by moaz-eldefrawy** [comment]
The link is not working ?

**Comment by shehabadel** [comment]
> The link is not working ?

Try to copy it in your browser

http://www.stackinfo.me
