### ISSUE TITLE
Is it paid?

### ISSUE THREAD

**Issue by xUser5000** [ACM-Alexandria-SC/Internships#3]
I think it will be useful to include for each internship whether or not it is paid. Some people, including me, consider this a major factor.
Thanks for your effort and I hope you keep maintaining this repository.

**Comment by ahr9n** [comment]
I agree.
Also, I suggest having a separate markdown file (like an archive) for closed internships. There is no need to remove their rows at all or to still having them among the active ones, however an archive would help to get more information of companies that held internships and so on.
